### ISSUE TITLE
Ordered Array when parsing configuration values

### ISSUE THREAD

**Issue by ph** [elastic/go-ucfg#103]
Let's say we want to create a  mapping table to replace values from an **integer** to a **string**, this is currently not possible with the current config type casting.

**Example:**

```yaml
potato:
  1: "abc"
  2: "oko"
  50: "noo"
```

When loaded from ucfg, the index is dropped.
```yaml
potato:
  - "abc"
  - "oko"
  - "noo"
```

Even if you escape the key as a string, it will lost the index.
```yaml
potato:
  "1": "abc"
  "2": "oko"
  "50": "noo"

potato:
  - "abc"
  - "oko"
  - "noo"
```

**Comment by ph** [comment]
@urso updated with our example from our talk.

**Comment by adriansr** [comment]
I've experienced this problem too.

In my use case, what I wanted was to be able to reference values inside arrays in Beats configuration:
```yaml
drop_event:
  when:
     equals:
        csv.4: false
```

Given this input, the output of go-ucfg is:
```json
"csv": [null, null, null, null, false]
```

Furthermore, for large numbers used as a key, this implies go-ucfg will try to allocate a very large array and possibly OOM the runtime.
