### ISSUE TITLE
Unable to unpack slices from docker labels

### ISSUE THREAD

**Issue by hamiltont** [elastic/go-ucfg#170]
Not sure if this is an issue with go-ucfg or perhaps filebeat is using this project in the wrong manner. The end result is identical to what was reported in [this](https://discuss.elastic.co/t/filebeat-hints-based-autodiscovery-how-to-use-copy-fields-or-rename-processor-in-kubernetes-annotation/233476/5) support post - autodiscover does not work for any processors that require slices as part of their config, because unpacking a string to a slice causes issues

In `copy_fields` the config struct contains a slice ([link](https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/processors/actions/copy_fields.go#L39)). 

Attempting to autodiscover a `copy_fields` processor on docker fails because it is unable to unpack: 

    failed to unpack the configuration of copy processor: required 'object', but found 'string' in field 'processors.0.copy_fields.fields'

For reference, this is my current label on the docker container `"co.elastic.logs/processors.copy_fields.fields"` mapped to `"[{from:message, to:event.original}]"`. AFAIK, docker labels cannot be objects, only strings. In the linked support post you will see that many permutations of different strings have been tried, but no one has reported a way to successfully get the unpack to work.

**Comment by urso** [comment]
processors and fields are arrays each. I'm not sure how filebeat splits the setting and if it does some processing by it's own. But looking at the structures only a label like this might work:
`processors.<idx>.copy_fields.fields.0: name`.

**Comment by hamiltont** [comment]
@urso that was what I needed, thanks! Closing this b/c it's basically a documentation bug now. THe following works as expected: 

```
  labels:
      co.elastic.logs/module: traefik
      co.elastic.logs/processors.copy_fields.fields.0.from: message
      co.elastic.logs/processors.copy_fields.fields.0.to: event.original
      co.elastic.logs/processors.copy_fields.fail_on_error: "false"
      co.elastic.logs/processors.copy_fields.ignore_missing: "true"
```
